import { IArtefact } from './IArtefact';
import { IDocument } from './IDocument';
import { IIndividual } from './IIndividual';
import { SiteAttributes } from 'src/enums/site-type.enums';

export interface ISite {
  [SiteAttributes.SITE_ID]: number;
  [SiteAttributes.ENGLISH_NAME]: string;
  [SiteAttributes.FRENCH_NAME]: string;
  [SiteAttributes.KHMER_NAME]: string;
  [SiteAttributes.ALTERNATIVE_NAME]: string;
  [SiteAttributes.ALTERNATIVE_KHMER_NAME]: string;
  [SiteAttributes.DESCRIPTION]: string;
  [SiteAttributes.VERIFIED]: boolean;
  [SiteAttributes.VERIFICATION_DATE]: Date;
  [SiteAttributes.LOCATED_BY]: number;
  [SiteAttributes.CERAMICS_DETAILS]: string;
  [SiteAttributes.CERAMICS]: boolean;
  [SiteAttributes.BUILD_MATERIAL_COMMENTS]: string;
  [SiteAttributes.ARTEFACTS_COMMENTS]: string;
  [SiteAttributes.LOOTED]: boolean;
  [SiteAttributes.CULTIVATED]: boolean;
  [SiteAttributes.CLEARED]: boolean;
  [SiteAttributes.THREATENED]: boolean;
  [SiteAttributes.DATABASING_COMMENTS]: string;
  [SiteAttributes.CREATION_DATE]: Date;
  [SiteAttributes.MODIFICATION_DATE]: Date;
  [SiteAttributes.USER_CREATION]: string;
  [SiteAttributes.USER_MODIFICATION]: string;
  [SiteAttributes.STUDY_AREA]: string;
  [SiteAttributes.FEATURE_TYPE]: string;
  [SiteAttributes.DOCUMENTS]: IDocument[];
  [SiteAttributes.ARTEFACTS]: IArtefact[];
  [SiteAttributes.INDIVIDUALS]: IIndividual;
  [SiteAttributes.GROUND_VERIFIED_BY]: number;
  [SiteAttributes.MATERIAL_SANDSTONE]: boolean;
  [SiteAttributes.MATERIAL_PINK_SANDSTONE]: boolean;
  [SiteAttributes.MATERIAL_LATERITE]: boolean;
  [SiteAttributes.MATERIAL_BRICK]: boolean;
  [SiteAttributes.MATERIAL_THMAPHNOM]: boolean;
  [SiteAttributes.MATERIAL_OTHER]: boolean;
  [SiteAttributes.ARTEFACTS_PEDESTAL]: boolean;
  [SiteAttributes.ARTEFACTS_COLONETTE]: boolean;
  [SiteAttributes.ARTEFACTS_DOORFRAME]: boolean;
  [SiteAttributes.ARTEFACTS_STATUARY]: boolean;
  [SiteAttributes.ARTEFACTS_DECORATED_BLOCKS]: boolean;
  [SiteAttributes.ARTEFACTS_OTHER]: boolean;
  [SiteAttributes.ID_AMBIGUITY]: boolean;
  [SiteAttributes.ID_AMBIGUITY_DETAIL]: string;
  [SiteAttributes.IK_ID]: string;
  [SiteAttributes.MH_ID]: string;
  [SiteAttributes.CK_ID]: number;
  [SiteAttributes.IK_STARRED]: boolean;
  [SiteAttributes.BD_ID]: string;
  [SiteAttributes.GT_ID]: number;
  [SiteAttributes.CP_ID]: number;
  [SiteAttributes.DC_ID]: string;
  [SiteAttributes.GA_ID]: number;
  [SiteAttributes.JB_ID]: number;
  [SiteAttributes.EM_ID]: number;
  [SiteAttributes.PK_ID]: number;
  [SiteAttributes.IS_ID]: number;
  [SiteAttributes.COORDINATE_SOURCE]: string;
  [SiteAttributes.IN_GAP_STUDY_AREA]: boolean;
  [SiteAttributes.IN_LIDAR_STUDY_AREA]: boolean;
  [SiteAttributes.TO_BE_INVESTIGATED]: boolean;
  [SiteAttributes.TO_BE_REMAPPED]: boolean;
  [SiteAttributes.TO_BE_REMOVED]: boolean;
  [SiteAttributes.DB_RESOLVED]: number;
}

export interface ISiteList {
  siteId: number;
  siteName: string;
}
